### ISSUE TITLE
webpy failure stops process and does not restart

### ISSUE THREAD

**Issue by freekdk** [DShield-ISC/dshield#103]
I found the webpy service in failure status because a failure to connect to www4.dshield.org halts that process and does not restart or continues.

The error log shows:
mrt 17 03:27:09 rpi2tumhon python[13006]: Traceback (most recent call last):
mrt 17 03:27:09 rpi2tumhon python[13006]:   File "/srv/www/bin/web.py", line 40, in <module>
mrt 17 03:27:09 rpi2tumhon python[13006]:     local_pub_IP = requests.get('https://www4.dshield.org/api/myip?json', verify = False)
mrt 17 03:27:09 rpi2tumhon python[13006]:   File "/usr/lib/python2.7/site-packages/requests/api.py", line 72, in get
mrt 17 03:27:09 rpi2tumhon python[13006]:     return request('get', url, params=params, **kwargs)
mrt 17 03:27:09 rpi2tumhon python[13006]:   File "/usr/lib/python2.7/site-packages/requests/api.py", line 58, in request
mrt 17 03:27:09 rpi2tumhon python[13006]:     return session.request(method=method, url=url, **kwargs)
mrt 17 03:27:09 rpi2tumhon python[13006]:   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
mrt 17 03:27:09 rpi2tumhon python[13006]:     resp = self.send(prep, **send_kwargs)
mrt 17 03:27:09 rpi2tumhon python[13006]:   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
mrt 17 03:27:09 rpi2tumhon python[13006]:     r = adapter.send(request, **kwargs)
mrt 17 03:27:09 rpi2tumhon python[13006]:   File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
mrt 17 03:27:09 rpi2tumhon python[13006]:     raise ConnectionError(e, request=request)
mrt 17 03:27:09 rpi2tumhon python[13006]: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www4.dshield.org', port=443
mrt 17 03:27:09 rpi2tumhon systemd[1]: webpy.service: Main process exited, code=exited, status=1/FAILURE
mrt 17 03:27:09 rpi2tumhon systemd[1]: webpy.service: Unit entered failed state.
mrt 17 03:27:09 rpi2tumhon systemd[1]: webpy.service: Failed with result 'exit-code'.

**Comment by freekdk** [comment]
Just made the suggested change, although this problem did not occur anymore.
