### ISSUE TITLE
Cowrie does not start

### ISSUE THREAD

**Issue by parthdmaniar** [DShield-ISC/dshield#126]
I have referred to issue #119  and mine does not appear to be similar.

I have tried multiple installation of DShield's honeypot on an RPi running Raspbian Strech Lite. I have not changed anything on the Pi except the password. I have followed instructions as they are on the GitHub page. While  installation goes smooth and I can see firewall logs, I am unable to upload Cowrie logs due to the deamon not starting. Here is the diagnostic output.

```
Unit cowrie.service has begun starting up.
May 12 00:55:12 HPT cowrie[29143]: Join the Cowrie community at: http://bit.ly/cowrieslack
May 12 00:55:12 HPT cowrie[29143]: Using default Python virtual environment "/srv/cowrie/cowrie-env"
May 12 00:55:12 HPT cowrie[29143]: Starting cowrie: [twistd   --umask 0022 --pidfile var/run/cowrie.pid --logger cowrie.python.logfile.logger cowrie ]...
May 12 00:55:15 HPT cowrie[29143]: Unhandled Error
May 12 00:55:15 HPT cowrie[29143]: Traceback (most recent call last):
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 636, in parseOptions
May 12 00:55:15 HPT cowrie[29143]:     usage.Options.parseOptions(self, options)
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/usage.py", line 262, in parseOptions
May 12 00:55:15 HPT cowrie[29143]:     for (cmd, short, parser, doc) in self.subCommands:
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 653, in subCommands
May 12 00:55:15 HPT cowrie[29143]:     for plug in sorted(plugins, key=attrgetter('tapname')):
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/plugin.py", line 213, in getPlugins
May 12 00:55:15 HPT cowrie[29143]:     allDropins = getCache(package)
May 12 00:55:15 HPT cowrie[29143]: --- <exception caught here> ---
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/plugin.py", line 171, in getCache
May 12 00:55:15 HPT cowrie[29143]:     provider = pluginModule.load()
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/modules.py", line 392, in load
May 12 00:55:15 HPT cowrie[29143]:     return self.pathEntry.pythonPath.moduleLoader(self.name)
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/reflect.py", line 308, in namedAny
May 12 00:55:15 HPT cowrie[29143]:     topLevelPackage = _importAndCheckStack(trialname)
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/reflect.py", line 255, in _importAndCheckStack
May 12 00:55:15 HPT cowrie[29143]:     reraise(excValue, excTraceback)
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/src/twisted/plugins/cowrie_plugin.py", line 54, in <module>
May 12 00:55:15 HPT cowrie[29143]:     import cowrie.core.realm
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/src/cowrie/core/realm.py", line 47, in <module>
May 12 00:55:15 HPT cowrie[29143]:     from cowrie.proxy import avatar as proxyavatar
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/src/cowrie/proxy/avatar.py", line 18, in <module>
May 12 00:55:15 HPT cowrie[29143]:     from cowrie.proxy import session as proxysession
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/src/cowrie/proxy/session.py", line 14, in <module>
May 12 00:55:15 HPT cowrie[29143]:     from twisted.conch.ssh import common, keys, session
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/conch/ssh/keys.py", line 18, in <module>
May 12 00:55:15 HPT cowrie[29143]:     import bcrypt
May 12 00:55:15 HPT cowrie[29143]: exceptions.ImportError: No module named bcrypt
May 12 00:55:15 HPT cowrie[29143]: Unhandled Error
May 12 00:55:15 HPT cowrie[29143]: Traceback (most recent call last):
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/usage.py", line 447, in __str__
May 12 00:55:15 HPT cowrie[29143]:     return self.getSynopsis() + '\n' + self.getUsage(width=None)
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/usage.py", line 484, in getUsage
May 12 00:55:15 HPT cowrie[29143]:     for (cmd, short, parser, desc) in self.subCommands:
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 653, in subCommands
May 12 00:55:15 HPT cowrie[29143]:     for plug in sorted(plugins, key=attrgetter('tapname')):
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/plugin.py", line 213, in getPlugins
May 12 00:55:15 HPT cowrie[29143]:     allDropins = getCache(package)
May 12 00:55:15 HPT cowrie[29143]: --- <exception caught here> ---
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/plugin.py", line 171, in getCache
May 12 00:55:15 HPT cowrie[29143]:     provider = pluginModule.load()
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/modules.py", line 392, in load
May 12 00:55:15 HPT cowrie[29143]:     return self.pathEntry.pythonPath.moduleLoader(self.name)
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/reflect.py", line 308, in namedAny
May 12 00:55:15 HPT cowrie[29143]:     topLevelPackage = _importAndCheckStack(trialname)
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/reflect.py", line 255, in _importAndCheckStack
May 12 00:55:15 HPT cowrie[29143]:     reraise(excValue, excTraceback)
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/src/twisted/plugins/cowrie_plugin.py", line 54, in <module>
May 12 00:55:15 HPT cowrie[29143]:     import cowrie.core.realm
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/src/cowrie/core/realm.py", line 47, in <module>
May 12 00:55:15 HPT cowrie[29143]:     from cowrie.proxy import avatar as proxyavatar
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/src/cowrie/proxy/avatar.py", line 18, in <module>
May 12 00:55:15 HPT cowrie[29143]:     from cowrie.proxy import session as proxysession
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/src/cowrie/proxy/session.py", line 14, in <module>
May 12 00:55:15 HPT cowrie[29143]:     from twisted.conch.ssh import common, keys, session
May 12 00:55:15 HPT cowrie[29143]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/conch/ssh/keys.py", line 18, in <module>
May 12 00:55:15 HPT cowrie[29143]:     import bcrypt
May 12 00:55:15 HPT cowrie[29143]: exceptions.ImportError: No module named bcrypt
May 12 00:55:15 HPT cowrie[29143]: Usage: twistd [options]
May 12 00:55:15 HPT cowrie[29143]: Options:
May 12 00:55:15 HPT cowrie[29143]:   -b, --debug          Run the application in the Python Debugger (implies
May 12 00:55:15 HPT cowrie[29143]:                        nodaemon),         sending SIGUSR2 will drop into
May 12 00:55:15 HPT cowrie[29143]:                        debugger
May 12 00:55:15 HPT cowrie[29143]:       --chroot=        Chroot to a supplied directory before running
May 12 00:55:15 HPT cowrie[29143]:   -d, --rundir=        Change to a supplied directory before running [default:
May 12 00:55:15 HPT cowrie[29143]:                        .]
May 12 00:55:15 HPT cowrie[29143]:   -e, --encrypted      The specified tap/aos file is encrypted.
May 12 00:55:15 HPT cowrie[29143]:       --euid           Set only effective user-id rather than real user-id.
May 12 00:55:15 HPT cowrie[29143]:                        (This option has no effect unless the server is running
May 12 00:55:15 HPT cowrie[29143]:                        as root, in which case it means not to shed all
May 12 00:55:15 HPT cowrie[29143]:                        privileges after binding ports, retaining the option to
May 12 00:55:15 HPT cowrie[29143]:                        regain privileges in cases such as spawning processes.
May 12 00:55:15 HPT cowrie[29143]:                        Use with caution.)
May 12 00:55:15 HPT cowrie[29143]:   -f, --file=          read the given .tap file [default: twistd.tap]
May 12 00:55:15 HPT cowrie[29143]:   -g, --gid=           The gid to run as.  If not specified, the default gid
May 12 00:55:15 HPT cowrie[29143]:                        associated with the specified --uid is used.
May 12 00:55:15 HPT cowrie[29143]:       --help           Display this help and exit.
May 12 00:55:15 HPT cowrie[29143]:       --help-reactors  Display a list of possibly available reactor names.
May 12 00:55:15 HPT cowrie[29143]:   -l, --logfile=       log to a specified file, - for stdout
May 12 00:55:15 HPT cowrie[29143]:       --logger=        A fully-qualified name to a log observer factory to use
May 12 00:55:15 HPT cowrie[29143]:                        for the initial log observer.  Takes precedence over
May 12 00:55:15 HPT cowrie[29143]:                        --logfile and --syslog (when available).
May 12 00:55:15 HPT cowrie[29143]:   -n, --nodaemon       don't daemonize, don't use default umask of 0077
May 12 00:55:15 HPT cowrie[29143]:   -o, --no_save        do not save state on shutdown
May 12 00:55:15 HPT cowrie[29143]:       --originalname   Don't try to change the process name
May 12 00:55:15 HPT cowrie[29143]:   -p, --profile=       Run in profile mode, dumping results to specified file.
May 12 00:55:15 HPT cowrie[29143]:       --pidfile=       Name of the pidfile [default: twistd.pid]
May 12 00:55:15 HPT cowrie[29143]:       --prefix=        use the given prefix when syslogging [default: twisted]
May 12 00:55:15 HPT cowrie[29143]:       --profiler=      Name of the profiler to use (profile, cprofile).
May 12 00:55:15 HPT cowrie[29143]:                        [default: cprofile]
May 12 00:55:15 HPT cowrie[29143]:   -r, --reactor=       Which reactor to use (see --help-reactors for a list of
May 12 00:55:15 HPT cowrie[29143]:                        possibilities)
May 12 00:55:15 HPT cowrie[29143]:   -s, --source=        Read an application from a .tas file (AOT format).
May 12 00:55:15 HPT cowrie[29143]:       --savestats      save the Stats object rather than the text output of the
May 12 00:55:15 HPT cowrie[29143]:                        profiler.
May 12 00:55:15 HPT cowrie[29143]:       --spew           Print an insanely verbose log of everything that happens.
May 12 00:55:15 HPT cowrie[29143]:                        Useful when debugging freezes or locks in complex code.
May 12 00:55:15 HPT cowrie[29143]:       --syslog         Log to syslog, not to file
May 12 00:55:15 HPT cowrie[29143]:   -u, --uid=           The uid to run as.
May 12 00:55:15 HPT cowrie[29143]:       --umask=         The (octal) file creation mask to apply.
May 12 00:55:15 HPT cowrie[29143]:       --version        Print version information and exit.
May 12 00:55:15 HPT cowrie[29143]:   -y, --python=        read an application from within a Python file (implies
May 12 00:55:15 HPT cowrie[29143]:                        -o)
May 12 00:55:15 HPT cowrie[29143]: twistd reads a twisted.application.service.Application out of a file and runs
May 12 00:55:15 HPT cowrie[29143]: it.
May 12 00:55:15 HPT cowrie[29143]: Commands:
May 12 00:55:15 HPT cowrie[29143]:     conch            A Conch SSH service.
May 12 00:55:15 HPT cowrie[29143]:     dns              A domain name server.
May 12 00:55:15 HPT cowrie[29143]:     ftp              An FTP server.
May 12 00:55:15 HPT cowrie[29143]:     inetd            An inetd(8) replacement.
May 12 00:55:15 HPT cowrie[29143]:     mail             An email service
May 12 00:55:15 HPT cowrie[29143]:     manhole          An interactive remote debugger service accessible via
May 12 00:55:15 HPT cowrie[29143]:                      telnet and ssh and providing syntax coloring and basic line
May 12 00:55:15 HPT cowrie[29143]:                      editing functionality.
May 12 00:55:15 HPT cowrie[29143]:     news             A news server.
May 12 00:55:15 HPT cowrie[29143]:     portforward      A simple port-forwarder.
May 12 00:55:15 HPT cowrie[29143]:     procmon          A process watchdog / supervisor
May 12 00:55:15 HPT cowrie[29143]:     socks            A SOCKSv4 proxy service.
May 12 00:55:15 HPT cowrie[29143]:     web              A general-purpose web server which can serve from a
May 12 00:55:15 HPT cowrie[29143]:                      filesystem or application resource.
May 12 00:55:15 HPT cowrie[29143]:     words            A modern words server
May 12 00:55:15 HPT cowrie[29143]:     xmpp-router      An XMPP Router server
May 12 00:55:15 HPT cowrie[29143]: /srv/cowrie/cowrie-env/bin/twistd: Unknown command: cowrie
May 12 00:55:15 HPT systemd[1]: cowrie.service: PID file /srv/cowrie/var/run/cowrie.pid not readable (yet?) after start: No such file or directory
May 12 00:55:15 HPT systemd[1]: Failed to start Cowrie SSH and Telnet Honeypot.
-- Subject: Unit cowrie.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit cowrie.service has failed.
-- 
-- The result is failed.
May 12 00:55:15 HPT systemd[1]: cowrie.service: Unit entered failed state.
May 12 00:55:15 HPT systemd[1]: cowrie.service: Failed with result 'resources'.
May 12 00:55:15 HPT systemd[1]: cowrie.service: Service hold-off time over, scheduling restart.
May 12 00:55:15 HPT systemd[1]: Stopped Cowrie SSH and Telnet Honeypot.
-- Subject: Unit cowrie.service has finished shutting down
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit cowrie.service has finished shutting down.
May 12 00:55:15 HPT systemd[1]: Starting Cowrie SSH and Telnet Honeypot...
-- Subject: Unit cowrie.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit cowrie.service has begun starting up.
May 12 00:55:15 HPT cowrie[29152]: Join the Cowrie community at: http://bit.ly/cowrieslack
May 12 00:55:15 HPT cowrie[29152]: Using default Python virtual environment "/srv/cowrie/cowrie-env"
May 12 00:55:15 HPT cowrie[29152]: Starting cowrie: [twistd   --umask 0022 --pidfile var/run/cowrie.pid --logger cowrie.python.logfile.logger cowrie ]...
```

Could someone please help me fix this issue?

**Comment by parthdmaniar** [comment]
I can see a file 
`-rw-r--r-- 1 cowrie cowrie   11 Aug  6  2018 .gitignore
`
under 
`/srv/cowrie/var/run `

which if I cat gives following output:
```
pi@HPT:/srv/cowrie/var/run $ cat .gitignore
cowrie.pid
```

**Comment by s-m-r** [comment]
I am experiencing the same issue, I have also tried to install several times using the posted instructions.
My logs are very similar to the posted ones, appears to fail with bcrypt.

**Comment by s-m-r** [comment]
Had a discussion with the _cowrie_ team and the resolution is:
`
**cd /srv/cowrie
.  cowrie-env/bin/activate
pip install bcrypt
exit**


It took a bit of time to install/setup _bcrypt_; but once it was complete, _cowrie_ started up properly.

The final fix is to update the install scripts to use the current version of _cowrie_ as this issue is resolved is that version.

**Comment by jullrich** [comment]
Thanks a lot! I love it when problems get fixed before I even have a chance to look at them. Will add bcrypt to the install script.

**Comment by jullrich** [comment]
fixed

**Comment by parthdmaniar** [comment]
Does the big discovery get a free Raspberry Pi 3 B+


With warm regards,

Parth D. Maniar, CISSP, CISM, CISA, SSCP (ret.)
MSc in Software and Systems Security.
Kellogg College,
Oxford University.

Mobile Number: +91-9662355555

Alternate E-Mail ID: parth_maniar@hotmail.com

________________________________
