### ISSUE TITLE
Rebuilt RPi2 honeypot, but doesn't seem to be accepting/recording SSH via cowrie

### ISSUE THREAD

**Issue by ktrue** [DShield-ISC/dshield#22]
My RPi2 running jessie lite seized up and had to be rebuilt.  I used 2016-09-23-raspbian-jessie-lite image on a 32GB card, did password, hostname, file system expansion, reboot, 
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install git
git clone https://github.com/DShield-ISC/dshield.git
sudo dshield/bin/install.sh

Followed all the prompts of the install.sh script and it successfully completed.  Rebooted, then opened the DMZ to it's IP address.

Running bin/status.sh shows the SSH firewall logs are flowing upward, but the Last ssh Log Received: 2016-10-10 04:18:35 is stuck in the past.  Tried connecting to the cowrie SSH honeypot on 22 and 2222, and get 'connection refused'.   I'm not sure the cowrie honeypot is fully functional.. 

Where should I look next?

**Comment by ktrue** [comment]
More info.. did a sudo /srv/cowrie/stop.sh then this:

pi@TRP2HP:/srv/cowrie $ sudo ./start.sh
Starting cowrie with extra arguments [] ...
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 604, in parseOptions
    usage.Options.parseOptions(self, options)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 261, in parseOptions
    for (cmd, short, parser, doc) in self.subCommands:
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 621, in subCommands
    for plug in sorted(plugins, key=attrgetter('tapname')):
  File "/usr/lib/python2.7/dist-packages/twisted/plugin.py", line 209, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/plugin.py", line 167, in getCache
    provider = pluginModule.load()
  File "/usr/lib/python2.7/dist-packages/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/usr/lib/python2.7/dist-packages/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/usr/lib/python2.7/dist-packages/twisted/python/reflect.py", line 250, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/srv/cowrie/twisted/plugins/cowrie_plugin.py", line 46, in <module>
    from cowrie.core.config import readConfigFile
  File "/srv/cowrie/cowrie/core/config.py", line 8, in <module>
    import configparser
exceptions.ImportError: No module named configparser
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 450, in __str__
    return self.getSynopsis() + '\n' + self.getUsage(width=None)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 486, in getUsage
    for (cmd, short, parser, desc) in self.subCommands:
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 621, in subCommands
    for plug in sorted(plugins, key=attrgetter('tapname')):
  File "/usr/lib/python2.7/dist-packages/twisted/plugin.py", line 209, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/plugin.py", line 167, in getCache
    provider = pluginModule.load()
  File "/usr/lib/python2.7/dist-packages/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/usr/lib/python2.7/dist-packages/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/usr/lib/python2.7/dist-packages/twisted/python/reflect.py", line 250, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/srv/cowrie/twisted/plugins/cowrie_plugin.py", line 46, in <module>
    from cowrie.core.config import readConfigFile
  File "/srv/cowrie/cowrie/core/config.py", line 8, in <module>
    import configparser
exceptions.ImportError: No module named configparser
Usage: twistd [options]
Options:
      --savestats      save the Stats object rather than the text output of the
                       profiler.
  -o, --no_save        do not save state on shutdown
  -e, --encrypted      The specified tap/aos file is encrypted.
  -n, --nodaemon       don't daemonize, don't use default umask of 0077
      --originalname   Don't try to change the process name
      --syslog         Log to syslog, not to file
      --euid           Set only effective user-id rather than real user-id.
                       (This option has no effect unless the server is running
                       as root, in which case it means not to shed all
                       privileges after binding ports, retaining the option to
                       regain privileges in cases such as spawning processes.
                       Use with caution.)
  -l, --logfile=       log to a specified file, - for stdout
      --logger=        A fully-qualified name to a log observer factory to use
                       for the initial log observer. Takes precedence over
                       --logfile and --syslog (when available).
  -p, --profile=       Run in profile mode, dumping results to specified file
      --profiler=      Name of the profiler to use (profile, cprofile, hotshot).
                       [default: hotshot]
  -f, --file=          read the given .tap file [default: twistd.tap]
  -y, --python=        read an application from within a Python file (implies
                       -o)
  -s, --source=        Read an application from a .tas file (AOT format).
  -d, --rundir=        Change to a supplied directory before running [default:
                       .]
      --prefix=        use the given prefix when syslogging [default: twisted]
      --pidfile=       Name of the pidfile [default: twistd.pid]
      --chroot=        Chroot to a supplied directory before running
  -u, --uid=           The uid to run as.
  -g, --gid=           The gid to run as.
      --umask=         The (octal) file creation mask to apply.
      --help-reactors  Display a list of possibly available reactor names.
      --version        Print version information and exit.
      --spew           Print an insanely verbose log of everything that happens.
                       Useful when debugging freezes or locks in complex code.
  -b, --debug          Run the application in the Python Debugger (implies
                       nodaemon), sending SIGUSR2 will drop into debugger
  -r, --reactor=       Which reactor to use (see --help-reactors for a list of
                       possibilities)
      --help           Display this help and exit.

twistd reads a twisted.application.service.Application out of a file and runs
it.
Commands:
    conch            A Conch SSH service.
    dns              A domain name server.
    ftp              An FTP server.
    inetd            An inetd(8) replacement.
    mail             An email service
    manhole          An interactive remote debugger service accessible via
                     telnet and ssh and providing syntax coloring and basic line
                     editing functionality.
    manhole-old      An interactive remote debugger service.
    news             A news server.
    portforward      A simple port-forwarder.
    procmon          A process watchdog / supervisor
    socks            A SOCKSv4 proxy service.
    telnet           A simple, telnet-based remote debugging service.
    web              A general-purpose web server which can serve from a
                     filesystem or application resource.
    words            A modern words server
    xmpp-router      An XMPP Router server

/usr/bin/twistd: Unknown command: cowrie
pi@TRP2HP:/srv/cowrie $ netstat -an | grep "LISTEN "
tcp        0      0 0.0.0.0:12222           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN
tcp6       0      0 :::12222                :::*                    LISTEN
tcp6       0      0 :::25                   :::*                    LISTEN
pi@TRP2HP:/srv/cowrie $

I don't see anything listening on 2222 or 22 and there were error messages in the startup..

Help?

**Comment by ktrue** [comment]
This is still an issue.. nothing listening on the ssh port for cowrie, so no SSH logs submitted.

Additionally, today I ran:

cd dshield
git pull
sudo bin/install.sh

selected to delete/reinstall mySQL, got to the verify settings display, selected verify and the script dropped out with the message
![2017-03-24_thpissue](https://cloud.githubusercontent.com/assets/17507343/24315041/fc4f1d6a-10a1-11e7-85e0-a47b9da6caea.jpg)

I did a sudo reboot to restart the system.  It does appear to be collecting firewall logs, just not SSH logs

Last Web Log Received:
Last 404 Log Received:
Last ssh Log Received: 2016-10-10 04:18:35
Last ssh Firewall Log Received: 2017-03-24 21:45:19
Current Time/Date: 2017-03-24 21:57:00

**Comment by killamjr** [comment]
I am having a similar issue the cowrie honeypot does not appear to be listening after running the install

**Comment by killamjr** [comment]
I did get the ssh honey pot running, I first loaded some additional dependancies referenced from cowries github, I'm not sure which ones were vital so i loaded all of them.
https://github.com/micheloosterhof/cowrie/blob/master/INSTALL.md
then i generated the virtual environment in the cowrie folder location in /srv/cowrie with
$ pwd
/srv/cowrie
"sudo virtualenv cowrie-env"
Then when i tried to run cowrie it complained about a module named "logger" being missing in twisted so i ran the command the loads all the dependencies associated with cowrie from requirements.txt
"sudo pip install -U -r requirements.txt"
THEN cowrie was able to start and the logs show it is reporting to dshield

**Comment by jullrich** [comment]
I will take a look. maybe an issue with an updated cowrie version requiring more dependencies. but certainly not wrong to load them.

**Comment by ktrue** [comment]
Did a 
cd dshield
git pull
(installed the new install.sh)

sudo bin/install.sh

it completed, but still no cowrie start, and nothing listening on port 22

cd /srv/cowrie
sudo virtualenv cowrie-env
[code]Running virtualenv with interpreter /usr/bin/python2
New python executable in cowrie-env/bin/python2
Also creating executable in cowrie-env/bin/python
Installing setuptools, pip...done.
[/code]

then
sudo bin/cowrie start 

and received
[code]Activating virtualenv "cowrie-env"
Starting cowrie with extra arguments [ ] ...
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 604, in parseOptions
    usage.Options.parseOptions(self, options)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 261, in parseOptions
    for (cmd, short, parser, doc) in self.subCommands:
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 621, in subCommands
    for plug in sorted(plugins, key=attrgetter('tapname')):
  File "/usr/lib/python2.7/dist-packages/twisted/plugin.py", line 209, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/plugin.py", line 167, in getCache
    provider = pluginModule.load()
  File "/usr/lib/python2.7/dist-packages/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/usr/lib/python2.7/dist-packages/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/usr/lib/python2.7/dist-packages/twisted/python/reflect.py", line 250, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/srv/cowrie/twisted/plugins/cowrie_plugin.py", line 45, in <module>
    from twisted.logger import ILogObserver, globalLogPublisher
exceptions.ImportError: No module named logger
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 450, in __str__
    return self.getSynopsis() + '\n' + self.getUsage(width=None)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 486, in getUsage
    for (cmd, short, parser, desc) in self.subCommands:
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 621, in subCommands
    for plug in sorted(plugins, key=attrgetter('tapname')):
  File "/usr/lib/python2.7/dist-packages/twisted/plugin.py", line 209, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/plugin.py", line 167, in getCache
    provider = pluginModule.load()
  File "/usr/lib/python2.7/dist-packages/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/usr/lib/python2.7/dist-packages/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/usr/lib/python2.7/dist-packages/twisted/python/reflect.py", line 250, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/srv/cowrie/twisted/plugins/cowrie_plugin.py", line 45, in <module>
    from twisted.logger import ILogObserver, globalLogPublisher
exceptions.ImportError: No module named logger
[/code] as errata.

**Comment by killamjr** [comment]
I got this error too, its caused by the version of twisted being out of date, you need to run
"sudo pip install -U -r requirements.txt"
from the cowrie folder, this upgrades twisted and pulls in some other dependancies found in the requirements.txt file

**Comment by ktrue** [comment]
Tried:

 sudo pip install -U -r requirements.txt
Downloading/unpacking twisted>=15.2.1 (from -r requirements.txt (line 1))
  Downloading Twisted-17.1.0.tar.bz2 (3.0MB): 3.0MB downloaded
  Running setup.py (path:/tmp/pip-build-Mja63C/twisted/setup.py) egg_info for package twisted
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "/usr/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 14, in <module>
        from setuptools.command.sdist import sdist
      File "/usr/lib/python2.7/dist-packages/setuptools/command/sdist.py", line 9, in <module>
        from setuptools import svn_utils
      File "/usr/lib/python2.7/dist-packages/setuptools/svn_utils.py", line 12, in <module>
        from setuptools.py31compat import TemporaryDirectory
      File "/usr/lib/python2.7/dist-packages/setuptools/py31compat.py", line 2, in <module>
        import unittest
      File "/usr/lib/python2.7/unittest/__init__.py", line 58, in <module>
        from .result import TestResult
    ValueError: bad marshal data (unknown type code)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 3, in <module>

  File "/usr/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 14, in <module>

    from setuptools.command.sdist import sdist

  File "/usr/lib/python2.7/dist-packages/setuptools/command/sdist.py", line 9, in <module>

    from setuptools import svn_utils

  File "/usr/lib/python2.7/dist-packages/setuptools/svn_utils.py", line 12, in <module>

    from setuptools.py31compat import TemporaryDirectory

  File "/usr/lib/python2.7/dist-packages/setuptools/py31compat.py", line 2, in <module>

    import unittest

  File "/usr/lib/python2.7/unittest/__init__.py", line 58, in <module>

    from .result import TestResult

ValueError: bad marshal data (unknown type code)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-Mja63C/twisted
Storing debug log for failure in /root/.pip/pip.log

I think I'm going to try a rebuild from scratch.. this is getting a bit crazy...

**Comment by K4KDR** [comment]
FYI, same errors as ktrue.  As this is a dedicated system and has never been used for anything but the dshield honeypot, our systems are probably identical.

**Comment by ktrue** [comment]
Did a fresh build with raspian-jessie-lite, the usual apt-get update/upgrade and raspi-config for password/hostname/expand filesystem.  Reboot, installed git, git clone of dshield and run the bin/install.sh script to completion.

No joy.. still no cowrie, and nothing listening on port 22.  

During install, I saw this message:

Adding / updating cowrie user in MySQL.
ERROR 1396 (HY000) at line 1: Operation DROP USER failed for 'cowrie'@'*'

but that was the only 'out of ordinary' error spotted.

**Comment by jullrich** [comment]
Thanks. i will try another install later. The error you spotted is only related to MySQL and should not effect ssh.

**Comment by gebhard73** [comment]
should be solved with pull request #33

**Comment by ktrue** [comment]
Yes, this is fixed with pull req #33.   Thanks gebhard73 for all your work on this.  My honeypot is now reporting SSH activity again!
