### ISSUE TITLE
isc-agent randomly crashes

### ISSUE THREAD

**Issue by Betskvanting** [DShield-ISC/dshield#281]
This happends 2-4 times/day
####
DEBUG :: 2023-08-09 23:25:59,069 :: <PID 620:MainProcess> :: urllib3.connectionpool :: L:473 :: https://www.dshield.org:443 "GET /api/honeypotrules/ HTTP/1.1" 200 None
DEBUG :: 2023-08-09 23:30:47,899 :: <PID 620:MainProcess> :: plugins.tcp.http.main :: L:105 :: [RequestLog(1), RequestLog(2), RequestLog(3), RequestLog(4), RequestLog(5), RequestLog(6)]
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/srv/isc-agent/virtenv/lib/python3.9/site-packages/twisted/internet/base.py", line 1318, in run
    self.mainLoop()
  File "/srv/isc-agent/virtenv/lib/python3.9/site-packages/twisted/internet/base.py", line 1328, in mainLoop
    reactorBaseSelf.runUntilCurrent()
  File "/srv/isc-agent/virtenv/lib/python3.9/site-packages/twisted/internet/base.py", line 994, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/srv/isc-agent/virtenv/lib/python3.9/site-packages/twisted/internet/task.py", line 251, in __call__
    d = maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/srv/isc-agent/virtenv/lib/python3.9/site-packages/twisted/internet/defer.py", line 206, in maybeDeferred
    result = f(*args, **kwargs)
  File "/srv/isc-agent/plugins/tcp/http/main.py", line 112, in submit_logs
    "logs": [rl.format_log_for_submission() for rl in request_logs],
  File "/srv/isc-agent/plugins/tcp/http/main.py", line 112, in <listcomp>
    "logs": [rl.format_log_for_submission() for rl in request_logs],
  File "/srv/isc-agent/plugins/tcp/http/models.py", line 53, in format_log_for_submission
    headers = json.loads(self.headers.replace("'", '"'))
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 49 (char 48)

**Comment by Betskvanting** [comment]
and its on RaspberryPi OS 64, fresh install since 2 days

**Comment by Betskvanting** [comment]
fixed
