### ISSUE TITLE
install.sh aborts in py install cryptography

### ISSUE THREAD

**Issue by ktrue** [DShield-ISC/dshield#88]
I did a git pull/ install.sh this morning and it terminated with
```
Downloading/unpacking cryptography>=0.9.1 (from -r requirements.txt (line 2))
  Running setup.py (path:/tmp/pip-build-HDgAiG/cryptography/setup.py) egg_info for package cryptography
    error in cryptography setup command: Invalid environment marker: python_version < '3'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: python_version < '3'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-HDgAiG/cryptography
Storing debug log for failure in /root/.pip/pip.log
2017-10-18_163145 ### DEBUG OUTPUT: EXIT CODE NOT ZERO (1)!
2017-10-18_163145 ### Error installing dependencies from requirements.txt.
```

**Comment by jullrich** [comment]
which version of Raspbian are you running? I am trying to reproduce this.

**Comment by ktrue** [comment]
raspian jessie lite

**Comment by jullrich** [comment]
hm. can't reproduce right now. I will have to re-test this with a fresh jessie lite install. Could you please try running this command before trying another install:

```
pip install --upgrade setuptools
```

**Comment by ktrue** [comment]
I ran the
```
sudo pip install --upgrade setuptools
```
then
```
sudo dshield/bin/install.sh
```
It still aborts with 
```
2017-10-20_133810 ### Running: pip install -r requirements.txt
Downloading/unpacking twisted>=17.1.0 (from -r requirements.txt (line 1))
  Running setup.py (path:/tmp/pip-build-pQDx47/twisted/setup.py) egg_info for package twisted
    no previously-included directories found matching '.travis'
    no previously-included directories found matching 'tests'
    warning: no previously-included files found matching 'examplesetup.py'
    no previously-included directories found matching 'src/exampleproj'
    no previously-included directories found matching 'src/incremental/newsfragments'

    Installed /tmp/pip-build-pQDx47/twisted/incremental-17.5.0-py2.7.egg

    warning: no previously-included files matching '*.misc' found under directory 'src/twisted'
    warning: no previously-included files matching '*.bugfix' found under directory 'src/twisted'
    warning: no previously-included files matching '*.doc' found under directory 'src/twisted'
    warning: no previously-included files matching '*.feature' found under directory 'src/twisted'
    warning: no previously-included files matching '*.removal' found under directory 'src/twisted'
    warning: no previously-included files matching 'NEWS' found under directory 'src/twisted'
    warning: no previously-included files matching 'README' found under directory 'src/twisted'
    warning: no previously-included files matching 'newsfragments' found under directory 'src/twisted'
    warning: no previously-included files found matching 'src/twisted/topfiles/CREDITS'
    warning: no previously-included files found matching 'src/twisted/topfiles/ChangeLog.Old'
    warning: no previously-included files found matching 'pyproject.toml'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files found matching 'appveyor.yml'
    no previously-included directories found matching 'bin'
    no previously-included directories found matching 'admin'
    no previously-included directories found matching '.travis'
    warning: no previously-included files found matching 'docs/historic/2003'
    warning: no previously-included files matching '*' found under directory 'docs/historic/2003'
Downloading/unpacking cryptography>=0.9.1 (from -r requirements.txt (line 2))
  Running setup.py (path:/tmp/pip-build-pQDx47/cryptography/setup.py) egg_info for package cryptography
    error in cryptography setup command: Invalid environment marker: python_version < '3'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: python_version < '3'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-pQDx47/cryptography
Storing debug log for failure in /root/.pip/pip.log
2017-10-20_133836 ### DEBUG OUTPUT: EXIT CODE NOT ZERO (1)!
2017-10-20_133836 ### Error installing dependencies from requirements.txt. See /srv/log/install_2017-10-20_133433.log for details.
```

**Comment by ktrue** [comment]
I'm doing a fresh build from raspian stretch lite .. I'll let you know how that goes

**Comment by ktrue** [comment]
Tried a fresh build on raspian stretch lite this evening.  install.sh fails with
```
Collecting prettytable>=0.7.2 (from csirtgsdk>=0.0.0a6->-r requirements-output.txt (line 2))
Exception:
Traceback (most recent call last):
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/srv/cowrie/cowrie-env/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/srv/cowrie/cowrie-env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/srv/cowrie/cowrie-env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
2017-10-23_052240 ### DEBUG OUTPUT: EXIT CODE NOT ZERO (2)!
2017-10-23_052240 ### Error installing dependencies from requirements-output.txt. See /srv/log/install_2017-10-23_050134.log for details.
```

**Comment by ktrue** [comment]
As a side note, I noticed the different name for the primary ethernet port.. used to be 'eth0'.  now it shows
```
 ifconfig
enxb827ebcdf7ec: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.115  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::23d0:d0ec:b102:3c52  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:cd:f7:ec  txqueuelen 1000  (Ethernet)
        RX packets 55170  bytes 78335796 (74.7 MiB)
        RX errors 0  dropped 6  overruns 0  frame 0
        TX packets 23183  bytes 2099708 (2.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
...
```
Would that make a difference?

**Comment by ktrue** [comment]
I'm now trying a fresh install using 2017-09-07-raspbian-stretch-lite.img

Will post results when finished.

**Comment by jullrich** [comment]
Thanks! I will have to wait until I get back home to my Pi to work on this. The install script should deal with the more complex interface names that show up in current Linux distros. But have to see if it works with that particular name. Sad that linux is moving away from the simple names to more driver specific names :(

**Comment by jullrich** [comment]
(this also does look a bit like a cowrie issue. I will see if they have a resolution for this)

**Comment by ktrue** [comment]
I tried the 'Hail Mary' (see #90 ) of:

```
sudo su -
apt-get update; apt-get -y upgrade; apt-get -y dist-upgrade
pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
pip install -r /srv/cowrie/requirements.txt
pip install -r /srv/cowrie/requirements-output.txt
```
then ran install.sh successfully.   I've put the updated HP system online, and it is reporting

Last Web Log Received:
Last 404 Log Received: 2017-11-09 05:15:48
Last ssh Log Received: 2017-11-09 04:45:39
Last ssh Firewall Log Received: 2017-11-09 05:15:28
Current Time/Date: 2017-11-09 05:31:12

**Comment by jullrich** [comment]
Excellent! Thanks for solving this issue.
