### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by bdmeyer** [DShield-ISC/dshield#90]
My 1 year old SD-CARD finally gave up the ghost with lots of bad blocks from the original version of this honeypot, so I just did a new install from scratch using Raspbian Stretch  Light.

The install ended with this error:
`  File "/srv/cowrie/cowrie-env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
2017-10-31_171800 ### DEBUG OUTPUT: EXIT CODE NOT ZERO (2)!
2017-10-31_171800 ### Error installing dependencies from requirements-output.txt. See /srv/log/install_2017-10-31_170039.log for details.

The last line is recursive as that is the log I was cat'ting.

Please let me know what info I can provide.

-= BDM

`

**Comment by gebhard73** [comment]
This seems to be a problem with the URLlib itself ... hopefully it will resolve in a few days with an update ...

Can't test it myself now unfortunately.

**Comment by bdmeyer** [comment]
I'll try a pull in a few days then. Thank-You


--Bruce D. Meyer


________________________________

**Comment by bdmeyer** [comment]
I didn't provide a traceback. Here is the full tracback:
Exception:
Traceback (most recent call last):
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/srv/cowrie/cowrie-env/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/srv/cowrie/cowrie-env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/srv/cowrie/cowrie-env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
2017-11-02_201757 ### DEBUG OUTPUT: EXIT CODE NOT ZERO (2)!
2017-11-02_201757 ### Error installing dependencies from requirements-output.txt. See /srv/log/install_2017-11-02_200627.log for details.

**Comment by bdmeyer** [comment]
I went to the cowrie site, where I got some great advice. The author said, when all else fails perform a 'Hail Mary' as the root user (sudo su -)
```
apt-get update; apt-get -y upgrade; apt-get -y dist-upgrade
pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
pip install -r /home/cowrie/cowrie/requirements.txt
```
The location of the requirements file is in a different location in the Dshield fork, so once having adjust for that, 'some of it was fixed. I next ran:
`pip install -r /home/cowrie/cowrie/requirements-output.txt`
and reran the install.sh, which now completed without any errors
.
The conversation is here:
[Fail in install at urllib #617](https://github.com/micheloosterhof/cowrie/issues/617#issuecomment-341596786)

I'll see if ssh and 404 is getting submitted over the next 24 hours.

Thank-You all for the great help!

-= BDM

**Comment by bdmeyer** [comment]
I don't know if you want me to close this or leave it open. I would think 'open' as to fix it, I had to do the 'pip install' for each of the requirements files.

**Comment by gebhard73** [comment]
the install script is only meant to work on a dedicated, fresh distro as mentioned in the README ... so I'd suggest closing the issue as long as it doesn't affect the clean install - thanks

**Comment by bdmeyer** [comment]
I must not be communicating very clearly. This IS a dedicated, fresh install that failed.
I was only able to fix it using help from the cowrie git hub forum.
What did I say that leads you to think this is not a dedicated fresh install?

**Comment by ktrue** [comment]
I also did a 'fresh' install using 2017-09-07-raspbian-stretch-lite and the following:

sudo raspi-config
  change hostname, password, expand filesystem, keyboard-104/US format, enable SSH
then
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo reboot

sudo apt-get install git
git clone https://github.com/DShield-ISC/dshield.git
cd dshield
sudo bin/install.sh
```
The install proceeds and then terminates with 
```
Collecting prettytable>=0.7.2 (from csirtgsdk>=0.0.0a6->-r requirements-output.txt (line 2))
Exception:
Traceback (most recent call last):
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/srv/cowrie/cowrie-env/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/srv/cowrie/cowrie-env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/srv/cowrie/cowrie-env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
2017-11-09_180526 ### DEBUG OUTPUT: EXIT CODE NOT ZERO (2)!
2017-11-09_180526 ### Error installing dependencies from requirements-output.txt. See /srv/log/install_2017-11-09_173822.log for details.
```

so I did the 'Hail Mary' fix (above) adapted for the location of cowrie:
```
sudo su -
pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
pip install -r /srv/cowrie/requirements.txt
pip install -r /srv/cowrie/requirements-output.txt
exit
sudo bin/install.sh
```
and it completed normally this time.
So.. I guess the install.sh script needs some mods in order to complete successfully the first time.

**Comment by jullrich** [comment]
just ran another install, and it worked fine. I am closing this as this looks like an issue with one of the pip packages that probably was fixed in the last couple days.
